### ISSUE TITLE
Can't open app, log-in

### ISSUE THREAD

**Issue by jwwiii1982** [nancpasc/ZattooBox#1]
I have access to Zattoo's website and have a premium account and when ever I try and open the add-on I receive the message, "Unable to start session. Check your account settings." I have my Username and Password correct.

**Comment by nancpasc** [comment]
Hi. It should work perfectly with a premium account. Can you tell me what is your version of Kodi/XBMC and what OS you are using ? In the meanwhile you can check that you are using the latest version of the addon (0.5.0) and double check that your credentials are correct. This message indicates that a session cannot be opened with the given username/password, or that the session cannot be cached. I'll investigate.

**Comment by jwwiii1982** [comment]
OK, I switched back to the Confluence skin in XBMC from Amber and I can open the app, but it isn't showing my favorite channels and I'm only getting 2 live channels, "SRF info" and "Deutsches Anleger Fernshen". I'm using AdFreeTime to access Zattoo. I have no problems as for as accessing everything in-browser, Chrome. My OS is Windows 8.1 and Kodi/XBMC version is Gotham 13.2 and version of Zattoo Box that is install in XBMC is 0.5.0.

**Comment by nancpasc** [comment]
Tried with same config + Amber skin and had no issue. As for the missing channels, there is a 'channels.cache'  file in the plugin data directory "%appdata%\XBMC\userdata\addon_data\plugin.video.zattoobox". Send it to zattoobox[at]outlook.com and I'll have a look.

**Comment by jwwiii1982** [comment]
Just sent you the email with channels.cache attached. Thanks.

**Comment by nancpasc** [comment]
I've checked your file and indeed, Zattoo API returns that only 2 channels are available for your account : "SRF info" and "Deutsches Anleger Fernsehen". What might happen is that Zattoo restrict channels depending on your geographic location. If you're watching Zattoo through a proxy, check that the same proxy is configured in XBMC. Also, you can try to remove all the *.cache files in the addon_data directory and retry once you've changed your settings.

**Comment by jwwiii1982** [comment]
I switched from AdFreeTime to UnoTelly for my DNS service and everything is
working beautifully. Thanks for your quick responses, is there anyway that
I can donate to you.

**Comment by nancpasc** [comment]
Glad the issue is solved. No worries I don't accept donations yet :)
