### ISSUE TITLE
ZDF stream is playing ARD

### ISSUE THREAD

**Issue by scrag** [nancpasc/ZattooBox#11]
I have noticed today that when the ZDF stream is selected it plays the ARD stream.

This only happens with the Kodi add-on. iPad plays the correct streams.

**Comment by nancpasc** [comment]
I can't reproduce. When I select ZDF HD it actually plays ZDF HD...

**Comment by scrag** [comment]
Ok, thanks.

I just tried it again today, this morning here, and the correct streams are playing for each channel.

I'll keep an eye on it but it may have been an issue at the Zattoo server end.

Regards

**Comment by scrag** [comment]
Issue seems to have been with Zattoo themselves. Selected ZDF stream at several times and it is now playing the correct stream.

Thank you.
