### ISSUE TITLE
Stream stops playing after several seconds

### ISSUE THREAD

**Issue by Luke1000** [nancpasc/ZattooBox#12]
The stream stops playing after several seconds. It seems that it is always the same amount of seconds.
I can start watching again by clicking on the desired channel again. After several seconds the stream stops again.
Pushing enter while watching the stream I can observe a bar that slowly reaches the right side and then the steam stops playing, like it was finished.
Seems to me, like there is just no video material anymore in buffer to play.

How to solve that problem? It's just imposible to enjoy a film, when it always stops playing after several seconds.

I'm using Kodi 14.2 and zattoobox 1.0.0 on an ubuntu linux with the spanish version of zattoo.

**Comment by nancpasc** [comment]
Hi.

If you can see the stream for a few seconds, then the addon is working properly. Might be indeed a buffering issue, or something related to your system. Try to play the following stream in Kodi : 

http://www.nasa.gov/multimedia/nasatv/NTV-Public-IPS.m3u8

If it fails, then you might want to contact Kodi directly.

regards.

**Comment by nancpasc** [comment]
Here is the link on Kodi How-to, if required.

http://kodi.wiki/view/Internet_video_and_audio_streams

**Comment by Luke1000** [comment]
Sorry for the late reponse, i was very busy lately.
I have tested the ntv link now (http://www.nasa.gov/multimedia/nasatv/NTV-Public-IPS.m3u8).

What I did: I downloaded the m3u8 file into a video directory of kodi with my other videos and used the file browser of kod to start the m3u8 file.
In 6 minutes watching I got one pause saying "buffering" with the nasa stream, then it continued.

With zattoobox I it always stops after 1 minute and some seconds. There is not even a buffering message. And it happens every time.
Any ideas?

**Comment by nancpasc** [comment]
Do not download the file just create a .strm as mentioned in the wiki.
If it does not work it means your system is unable to play this type of live stream.
It it works properly the issue is related to your zattoo account.
In any case, there is nothing I can do to help, addon-wise.

**Comment by Luke1000** [comment]
Both stream work fine, but zattoobox only works for about one minute.

The problem is not related the my zattoo account, as it works from my PC.

What would probably fix the problem is, if you could implement a  function in the addon, that the player doesn't stop, when there is no data in the buffer anymore, but pauses and does buffering.
Because this is what happens when I use the NASA stream.

**Comment by nancpasc** [comment]
The stream is handled 100% by Kodi, the addon doesn't control playback at all, it only redirects the stream. If there are issues with buffering, they must be addressed to Kodi. I consider this is the expected behaviour, Issue is closed.
