### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by sirsquall** [nancpasc/ZattooBox#14]
Hi,

First of all thanks you for this beautifull extension :)!

I don't know but I have some (tsr1, tsr2, m6) channel who have disapear, I have look in the iPhone app and in the zattoo website, and the channel are there.

Do you know why ? Or what I can do ?

I have downgrade the extension to the old one the 0.5.1 and the channel are there, so It seem's is only related to the 1.0 version.

Thanks

**Comment by nancpasc** [comment]
Hi,

I think it's related to issue #10.
Please try to deactivate "Hide watched" option for the LiveTV folder.

Regards.

**Comment by sirsquall** [comment]
Thanks a lot, everything is fine now :)
