### ISSUE TITLE
License

### ISSUE THREAD

**Issue by erdmannp** [nancpasc/ZattooBox#15]
Hi,

good work, i would like to know what License ZattooBox is. I try to use your code to view zattoo with mpv, i have a Allwinner device and i cannot use kodi... Please tell me if it is ok for you, that i publish my results ( with this site as reference.)

**Comment by nancpasc** [comment]
Hi,

Feel free to use / extend / modify this add-on as you wish. It is always appreciated if you keep the original copyright file somewhere within your distribution :-)

Regards.
