### ISSUE TITLE
Access "show now playing program (EPG)"

### ISSUE THREAD

**Issue by indritix** [nancpasc/ZattooBox#18]
Hi, thanks for this great addon!
Noticed you updated with EPG functionality, however this is not showing up for me.
How do I access the EPG?
Everything else works fine.
Using ReFocus skin on OSMC (Jarvis builds).

**Comment by gdomenici** [comment]
Patch author here. In fact it's not a proper EPG -- it's just showing the "now playing" and "next up" program as part of the channel name when in Live mode. You can enable it from the settings screen: "Show 'now playing' program next to the channel name".

If you look at this (long) conversation: https://github.com/nancpasc/ZattooBox/pull/17, near the bottom rainman74 mentions another ZattooBox fork that has a "proper" EPG implementation (by an author I don't know). Works fairly well, but it does have a few bugs.

**Comment by indritix** [comment]
Ok, I guess it might be a skin (ReFocus) related issue (unfortunately the option "Show now playing" doesn't show up in the settings screen, only username and password available)
As a workaround I'll try editing by hand the settings file and set the default to true:
<setting label="30003" type="bool" id="showNowPlayingProgram" default="false"/>"
Already using the ZattooBoxExt fork you mentioned, but as you said it's a bit buggy (that's why I'm trying to get your extension to work).
Will let you know, and thanks for the reply!

**Comment by indritix** [comment]
Hi, problem solved ;)
I was using the version downloaded from the Kodi repository which doesn't include the "now playing" function.
The one on GitHub works fine though, thanks a lot!

**Comment by gdomenici** [comment]
Good to hear... Maybe @nancpasc will submit it to the official Kodi repo one of these days?

**Comment by nancpasc** [comment]
:+1:  I gonna publish it under 1.0.1.

Regards!

**Comment by nancpasc** [comment]
Thank you everyone for the support. Please now use the excellent Zattoo PVR Client to access this feature. 

https://kodi.tv/addon/pvr-client/zattoo-pvr-client
