### ISSUE TITLE
Laggy performance with HD chanels

### ISSUE THREAD

**Issue by domvo** [nancpasc/ZattooBox#19]
Hi! I am using this Addon with Kodi on my Fire TV Stick. I have a Premium Zattoo subscription, which means I can watch many chanels in HD. 

Unfortunately, the HD playback is very unsmooth, laggy and stuttering. First second or two is fine, then it's inacceptable. I can definitely rule out my connection speed. In fact the native Zattoo app on the AFTV works like charm in terms of HD playback but is very unstable itself (crashes). Also other HD streams work fine in Kodi - even with 1080p it's butter smooth. 

Any suggestions?

**Comment by nancpasc** [comment]
Hi,

Unfortunately, I don't have any suggestion. Some other users did report similar issues, but I've never been able to reproduce myself.

**Comment by nancpasc** [comment]
Can't reproduce
