### ISSUE TITLE
Helix support?

### ISSUE THREAD

**Issue by chsigg** [nancpasc/ZattooBox#2]
I'm trying to install ZatooBox from a zip on Helix, and getting 'dependencies not met'. Are you aware of anything that needs to be done to support Helix? I'm happy to help, if I can.

**Comment by nancpasc** [comment]
Hi, thanks for the feedback. I'm aware it does not support Helix but the next update will. I planned to make the next release Helix compatible, and will be available in repository.

**Comment by chsigg** [comment]
That sounds great, thank you very much!

**Comment by nancpasc** [comment]
I made a minor adjustment to fix the dependency error. New release 0.5.1 is available and working on Helix.
