### ISSUE TITLE
Switch audio channel in kodi

### ISSUE THREAD

**Issue by meskilla** [nancpasc/ZattooBox#20]
Hello,

How can I switch audio tracks in kodi? I click the audio button and only see one track. When logged into the website I have two and can switch to 2nd language. When I open the browser debug window, I see it loads a new manifest while I click to change audio tracks. Looks like there are two manifests for the same recording/live channel.

any way to implement this into your kodi addon?

**Comment by nancpasc** [comment]
Hi,

Thanks for the feedback. I've not implemented dual audio yet. I keep this feature request open for the next update.

Regards.

**Comment by meskilla** [comment]
Keep me posted, thanks. You can test it on rts un/deux rsi 1/2 and srf 1/2. They recently changed to HD quality, I guess it was when they added the 2nd audio channel.

**Comment by bachp** [comment]
I would also really like to see this feature.

**Comment by robin24** [comment]
Hi there!

I also would love to have access to this feature... I'm fully blind and the second audio channel on some German TV stations contains audio descriptions for various movies and sports events, e.g. additional commentary on what is happening etc.
I know Zattoo makes it possible to switch to this audio channel, however unfortunately their website and iOS app are not very accessible to blind users. Therefore, having this feature in the Kodi addonp would be extremely awesome for me!
For testing purposes you could check out "Das Erste HD" and "ZDF HD", they usually broadcast audio descriptions on the second audio channel.

Many thanks, keep up the great work!
Robin

**Comment by nancpasc** [comment]
Thank you everyone for the support. Please now use the excellent Zattoo PVR Client to access this feature.

https://kodi.tv/addon/pvr-client/zattoo-pvr-client
