### ISSUE TITLE
RTS1 and RTS2 not visible on "live channel"

### ISSUE THREAD

**Issue by flabb17** [nancpasc/ZattooBox#22]
I'm using the addon on my Kodi installation
no problem with "recorded" tv show, but the "all chanels" and the "favorites" are not link at all to my list configure on zattoo online , and RTS1 and RTS2 are not visible at all !

but record from these channels are available 

thanks for the great plugin and your support

**Comment by flabb17** [comment]
On my Android devices, the list (favorite and all channel) is different, but some channel are missing too !

**Comment by nancpasc** [comment]
Hi,

Removing manually all the cache files (*.cache) in the zattoobox data folder might help to solve the problem. They'll be recreated automatically.

Best regards,

P.
