### ISSUE TITLE
ZattoBox don't work anymore

### ISSUE THREAD

**Issue by lawin1** [nancpasc/ZattooBox#24]
Since this December Zattoo Box 1.0.0 Kodi add-on ceased to work. LiveTV - all channels list doesn't show any channels.

**Comment by macscuol** [comment]
No Problems with RPi2 OpenElec 6.0.3 in Switzerland, maybe you expect DRM difficulties depending from what country you try to reach "your" channels - i had this problem with the same configuration from France ...

**Comment by lawin1** [comment]
Now it works for me again.

I use VPN with German and Switzerland IP. From both locations I was able to watch live channels trough Zattoo Box for many months. But for a couple of last weeks all channels list was empty. Then I tried a fork of this add-on - Zattoo Box Extended Beta. And this extended version worked for me, so I thought that the problem wasn't on my side. Well, think what you want, but after my post the original Zattoo Box started to stream live tv again. But maybe it's just a coincidence. After all, I'll close this issue.
