### ISSUE TITLE
Unable to start a session

### ISSUE THREAD

**Issue by schmic12** [nancpasc/ZattooBox#25]
Hello,

I installed the addon Zattoo Box and setup my username and password. However, I receive an error message "Unable to start a session. Check your account settings!".

I double-checked it on the zattoo website, where I can login flawlessly. I am a Zattoo HQ subscriber.

What's the problem or where can I find a detailed error log?

Thank you in advance and best regards
Michael

Additional info: I'm running Kodi v17.1 on Win10 x64. Network config without proxy or firewall.

**Comment by step21** [comment]
Same issue here. On another note, is it possible to enable showing the typed passwords for easier error correction?

**Comment by schmic12** [comment]
I'm pretty sure that I'm using and typing the correct password - I even tried copy/paste, but the error message stays. It would be nice if I could look up some log for troubleshooting. This message alone doesn't help :)

**Comment by nancpasc** [comment]
Hi, It's still working perfectly with my account. Please check the settings file in the following folder : addon_data\plugin.video.zattoobox\

if everything is fine, delete all the .cache files in that directory and try again.

**Comment by schmic12** [comment]
Thank you for your fast reply.

This is wierd. I installed the Win10 App verison of Kodi 17.1 RC and deleted the cache files - now it's working flawlessly...

Thank you for your support.

Best regards
Michael

**Comment by step21** [comment]
For me this still exists. The data in settings.xml is fine, but there are no cache files in this directory. This is under Ubuntu 16.04.1

**Comment by step21** [comment]
Kodi log says:
``00:16:52.138 T:139914927008128   ERROR: GetDirectory - Error getting plugin://plugin.video.zattoobox/
00:16:52.138 T:139914927008128   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zattoobox/) failed``

**Comment by Richard-st** [comment]
Has this issue on a pi (libreelec). Took a few minutes to locate settings.xml . All looked ok, then looked closer and there was a space at the end of my email address. Edited and removed space.  All good now

**Comment by cristofe47** [comment]
I am having the same problem. 

It looks like Zattoo have changed the way logging in works. Using an old account.cache that I had previously backed up solved the issue for me.

**Comment by nancpasc** [comment]
I'm sorry for all the hassle. I don't think Zattoo did change anything regarding the login process. If the login process works again using an old *.cache file, it most likely reveals a mistyped login or password. Please double check the credentials. Also, Thank you @Richard-st for sharing your solution. This might work for anyone encountering authentication issues. Please check extra spaces in settings.xml. Best regards.

**Comment by cristofe47** [comment]
Thank you for your answer.

I am very confident that my login and password are correct. I logged in on desktop literally by copying and pasting my login and pwd from the settings.xml file to be 100% sure I use the same.

I haven't touched the settings file in a while. 

Is the account.cache file going to expire at some point?

Please let me know if there's any information I can provide to help troubleshoot this. I enabled logging out didn't see anything relevant in the log.

Thanks
C.

**Comment by nancpasc** [comment]
Did you try to delete all the *.cache files and try again ? If this doesn't work, I gonna investigate further. Thanks.

**Comment by cristofe47** [comment]
I did, but it did not help. That's actually how I faced the problem :) I modified my favorite channels on the Zattoo app and I deleted the .cache files to have the changes taken into account in the app on Kodi. I couldn't login after I had deleted the .cache

Thanks for looking into this.

**Comment by nancpasc** [comment]
Ok, got it. If the session.cache does not exist, the login process won't work. I gonna try to fix this asap.

**Comment by cristofe47** [comment]
Great, thanks

**Comment by nancpasc** [comment]
Thanks for reporting the issue. A pull request is on the go, the fix will be available in the repository soon 👍

**Comment by cristofe47** [comment]
Brilliant, thank you for the quick fix

**Comment by nancpasc** [comment]
Solved in v1.0.3

**Comment by sirsquall** [comment]
Hello,

I just had a fresh install of openelect and zattoo box 1.0.6 and I have the same error message. what can i do?

Thanks,

**Comment by superaga** [comment]
> 
> 
> Hello,
> 
> I just had a fresh install of openelect and zattoo box 1.0.6 and I have the same error message. what can i do?
> 
> Thanks,

same for me with Archlinuxarm...

**Comment by sirsquall** [comment]
Install libreelec and pvr zattoo it work well

**Comment by superaga** [comment]
Hi @sirsquall I also tried that "set" and I don't get the authentication error although I can't start the stream. When I try to open the channel list menu It waits a bit (trying to open it) but It doesn't open... Is your system working well?
Cheers

**Comment by sirsquall** [comment]
Yes you need to go in the addons menu then setting of the pvr zattoo and you can configure the credentials and after is working well, you can go on tv

**Comment by superaga** [comment]
Hi @sirsquall, this is not the first time that I use Zatto.
I used to have it on a Raspbian installation (since 1 year...), but few weeks it stopped to work, then I decided to start with a new distro.
At the moment (my system - libreelec and pvr Zatto) looks good (installation and configuration) but it doesn't start...

**Comment by stschmidtmann** [comment]
Hi @,

I have the same issue with the login of the zattoo box 1.0.6 running on OpenELEC 8.0.4. I can successfully use the credentials from several devices. Also I changed my password. Zattoo Box always results in "Unable to start a session. Check your account settings!".

I have no ".cache" files to delete.
