### ISSUE TITLE
All the Channels are not working anymore

### ISSUE THREAD

**Issue by sirsquall** [nancpasc/ZattooBox#26]
Hello,

I use this extension since 2 years now, with 0 issue (thank you by the way), and since today, nothing is working anymore.

I have this message in the log file:
Playlist Player: skipping unplayable item:  0, path [plugin://plugin.video.zattoobox/?ext=Recording&mode=watch&id=1244432]

Any idea?

Thank you

**Comment by baac0** [comment]
Same here, livestreams stopped working today, log messages as in sirsqualls post.

Cheers
Achim

**Comment by catweazle10000** [comment]
I have the same problem here with the same log messages as above.

**Comment by crOld-code** [comment]
ssh go to: ~/.kodi/addons/plugin.video.zattoobox/resources/lib/core

find "zapisession.py" and change ZAPI_URL = 'https://zattoo.com'

**Comment by Valde91** [comment]
Many Thanks Cliquar! Your solution worked perfectly for me!

**Comment by nancpasc** [comment]
Hi everyone,

Thank you for pointing that out. Also, thank you @Cliquar for the suggested fix. I gonna update the addon in the repository asap.

Best wishes!

**Comment by sirsquall** [comment]
You are great! Everything work well!

Thank you very much!

**Comment by Glyder1** [comment]
The solution from Cliquar is for Linux I guess. What I have to do on Windows 10 maschine? Thanks in advance

**Comment by nancpasc** [comment]
Hi.

The addon is beeing processed in Kodi repository for an upgrade. Version 1.0.1 should be available tomorrow or so. Just upgrade the addon when available and everything will work like before.

Regards.

**Comment by Glyder1** [comment]
Hello,
thanks for your help Nancpasc, but the logon doesn't work. Some channels are not in HD and to change the channel takes a long time. My password is correct, because when I logon in a browser it works well. I try it on two different Windows 10 maschines with Kodi, but the same problem.
Thanks in advance for your help,
Olli
