### ISSUE TITLE
ZattooBox doesn't work since 4/20

### ISSUE THREAD

**Issue by m00sfett** [nancpasc/ZattooBox#27]
Hi!

Since April 20, ZattooBox does not work any more. I wrote the support and got the answer that they turned their stream from HTTP to HTTPS. Will there be a fix for the AddOn?

**Comment by m00sfett** [comment]
Hi again!

I found a way to make it work again:

(LibreELEC)
In the file /storage/.kodi/addons/plugin.zattoobox/resources/lib/core/zapisession.py change

> ZAPI_URL = 'http://zattoo.com'

to

> ZAPI_URL = 'https://zattoo.com'

**Comment by nancpasc** [comment]
Hi. Thanks for pointing this out. The URL change has been committed in the official Kodi Repository. Please upgrade the addon to v 1.0.1

Regards.
