### ISSUE TITLE
Update fails to play channels & scrambled channel listing

### ISSUE THREAD

**Issue by castalla** [nancpasc/ZattooBox#28]
1.  After recent update:  displays menus, but with a jumbled channel list (not the usual 'Swiss' listing)

2.  Each channel fails to play

**Comment by ghost** [comment]
I encounter the same issue although I randomly still get the chance to at least watch one channel every now and then.

**Comment by nancpasc** [comment]
Weird, I can't reproduce this. please try to clean the cache by deleting all the *.cache files in the following folder : addon_data/plugin.video.zattoobox (the physical path varies depending on the OS Kodi is running on)

**Comment by castalla** [comment]
Gets weirder!

Now working on Kodi 14.2 and 17.1  BUT not 16.6 (where account login fails)

edit: now working on 16.6

Excellent!
