### ISSUE TITLE
Zattoo HiQ & Recall

### ISSUE THREAD

**Issue by CptFuture** [nancpasc/ZattooBox#3]
Hi
i use your plugin with great success. Good work! At the moment, I have only a free zattoo account.
When I upgrade to the HiQ, does your plugin also support HD quality and the "recall" function?
Thanks.
  Andy

**Comment by nancpasc** [comment]
Hi. Thanks for the feedback. The plugin does supports HD. The available channels are automatically streamed in HD. There is no recall function. The only way to watch past programs is to add them manually in the recordings before watching.

**Comment by CptFuture** [comment]
Thanks for the fast answer. Have you got plans to implement the "recall" function in the near future?
This would be great!

**Comment by nancpasc** [comment]
no I don't plan to implement it in a near future.

**Comment by CptFuture** [comment]
ok, very sad!
Because the recall function is much more comfortable than the recorder.
It's pure "video on demand", which will be the future..

Regards
  Andy

Am 05.01.2015 um 19:15 schrieb nancpasc notifications@github.com:
