### ISSUE TITLE
ZattoBox Login Problem

### ISSUE THREAD

**Issue by Glyder1** [nancpasc/ZattooBox#30]
Hello,
the login doesn't work. Some channels are not in HD and to change the channel takes a long time. My password is correct, because when I logon in a browser it works well. I try it on two different Windows 10 maschines with Kodi, but the same problem.
Thanks in advance for your help,
Olli

**Comment by bplatypus** [comment]
Hi,

It's working... as newcomer to Kodi, I didn't get how to enter in the settings :-P (just right-click on the add-on and select settings).

edit: there's also another add-on available with SuperRepo (http://superrepo.org) called Zattoo HiQ

**Comment by nancpasc** [comment]
Hi, 

Please check with the latest version (#1.0.3)

All the best,
P.
