### ISSUE TITLE
[Leia 18 CE] Addon not longer working

### ISSUE THREAD

**Issue by gualtierogrey** [nancpasc/ZattooBox#32]
Just checked this morning and this addon is not longer working. It does load favourite channel list but other than that nothing happens. If developer is still behind this addon willing to send logs. this is on coreelec 8.90.1 leia 18 alpha using vpn. tested on android 7.1 same vpn works fine. thank you

**Comment by satellouk** [comment]
hello again, just an update. the addon is not actually working on the kodi 18 alpha tested on coreelec os. still fine on kodi 17 on android

**Comment by nancpasc** [comment]
Please check with the latest version (#1.0.3)
