### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by Jean28518** [nancpasc/ZattooBox#33]
Hi guys,
In Versin 1.0.1 in Kodi and 2.17.6 on Linux
Zattoo displays me that my login data is incorrect. But in the browser it is working quite fine.
Similar to #30 

[kodi.log](https://github.com/nancpasc/ZattooBox/files/2079617/kodi.log)

**Comment by achmetinternet** [comment]
I have a similar issue. Kodi version 17.6. Login data is correct but it tells me "Unable to start a session. Check your account settings!"

**Comment by Jean28518** [comment]
Thanks for your reply.
Which Account Settings? On Zattoo? I didn't find big Account Settings on Zattoo :/

**Comment by tsmaeder** [comment]
Using LibreElec 8.2.5 on a Raspi II, I consistently get the "Unable to start a session" message. Also checked with kodi 17.6 on my Fedora machine.

**Comment by Zero-Bytes** [comment]
I'm getting the same message. Seems Zattoo made changes to the login procedure.
"Zattoo Live TV" addon does not work also. Wrong login data message..

**Comment by nancpasc** [comment]
Hi, a fix will be published soon.

Best regards.

**Comment by nancpasc** [comment]
Version #1.0.3, which contains all the fixes, is now available in the repository.

All best,
P.
