### ISSUE TITLE
Python exception thrown with v.1.0.2

### ISSUE THREAD

**Issue by cristofe47** [nancpasc/ZattooBox#34]
Hi Pascal,

I am getting an error with v1.0.2: the addon starts but throws the error below when opening "LiveTV - favorite" or "LiveTV - all channels":

08:47:56.660 T:1332736928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('session',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.zattoobox/plugin.py", line 44, in <module>
                                                ext_class.activate_item(args)
                                              File "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/extensions/livetv.py", line 41, in activate_item
                                                self.build_channelsList(args)
                                              File "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/extensions/livetv.py", line 48, in build_channelsList
                                                channels = self.get_channels(args['cat'])
                                              File "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/extensions/livetv.py", line 126, in get_channels
                                                allChannels = self.get_allChannels(True if category == 'fav' else False)
                                              File "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/extensions/livetv.py", line 104, in get_allChannels
                                                channelsData = self.retrieve_channels()
                                              File "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/extensions/livetv.py", line 95, in retrieve_channels
                                                api = '/zapi/v2/cached/channels/%s?details=False' % self.ZapiSession.AccountData['session']['power_guide_hash']
                                            KeyError: ('session',)
                                            -->End of Python script error report<--
08:47:56.836 T:1947318448   ERROR: GetDirectory - Error getting plugin://plugin.video.zattoobox/?cat=fav&ext=LiveTV&mode=root
08:47:56.838 T:1947318448   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zattoobox/?cat=fav&ext=LiveTV&mode=root) failed

Deleting the *.cache files does not help: I am getting the error "unable to start session - check your login / password".

Thanks,
Christophe

**Comment by Ontario70** [comment]
Same here.

**Comment by nancpasc** [comment]
Hey, please remove all the .cache files after 1.0.2 upgrade. They aren't compatible anymore with the V2 authentication process. Best regards

**Comment by nancpasc** [comment]
I will try to automate this for the next upgrade ;)

**Comment by cristofe47** [comment]
I did delete the *.cache files, but I am still getting the same python exception

**Comment by Ontario70** [comment]
Same here.

 

Von: cristofe47 [mailto:notifications@github.com] 
Gesendet: Sonntag, 8. Juli 2018 20:24
An: nancpasc/ZattooBox <ZattooBox@noreply.github.com>
Cc: Ontario70 <olaf.lischke@gmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nancpasc/ZattooBox] Python exception thrown with v.1.0.2 (#34)

 

I did delete the *.cache files, but I am still getting the same python exception

**Comment by nancpasc** [comment]
I don't know what exactly happened with my latest commit, I must have done something wrong. My apologizes, I will update the repository asap.

In the meanwhile, if you know how to modify code files, you can update the following source code file plugin.video.zattoobox\resources\lib\core\zapisession.py and change the following lines : 
102 : api = '/zapi/session/hello' -> api = '/zapi/v2/session/hello'
112 : api = '/zapi/account/login' -> api = '/zapi/v2/account/login'

**Comment by cristofe47** [comment]
Thank you for the pointer. I made the changes in the code files and it's all working fine now.

Cheers, 
C.

**Comment by nancpasc** [comment]
Great to see that everything is working now. Version #1.0.3, which contains all the fixes, is now available in the repository.

All best,
P.
