### ISSUE TITLE
AttributeError  in zapisession.py in fetch_appToken

### ISSUE THREAD

**Issue by jgphpc** [nancpasc/ZattooBox#40]
Hi,

I am not sure how to fix this error i get when i am trying to start the plugin (version 1.0.5):

```
 File "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/core/zapisession.py", line 102, in fetch_appToken
return re.search("window\.appToken\s*=\s*'(.*)'", html).group(1)
 AttributeError: 'NoneType' object has no attribute 'group'
```

Here is the full [logfile](http://ix.io/2hgK).
Could you help me fix this ?

It is rather easy to reproduce (python2):

```python
import re
import urllib2
handle=urllib2.urlopen('https://zattoo.com/')
re.search("window\.appToken\s*=\s*'(.*)'", html)
# None
```

**Comment by evoisard** [comment]
Same issue here, since 7th of April (version 1.0.5)...

`
File "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/core/zapisession.py", line 102, in fetch_appToken
return re.search("window\.appToken\s*=\s*'(.*)'", html).group(1)
 AttributeError: 'NoneType' object has no attribute 'group'`

Maybe something has changed at Zattoo?...

More details in log abstract below:
[kodi.txt](https://github.com/nancpasc/ZattooBox/files/4455989/kodi.txt)

**Comment by rolfbachmann** [comment]
Same issue here. Probably something to do with the redirection. If you browse to the ZAPI_URL you will be redirected to the right site. If you disable Java Script you will not be redirected. Same behavior as with the `urlopen` function and you have to choose the destination (int, ch, de). On this page the `appToken` isn't available.

Change the URL in `resources/lib/core/zapisession.py`:
```
100	handle = urllib2.urlopen(self.ZAPI_URL + '/ch/')
```

Work for me, but depend on the country.

**Comment by SnowMonkeN** [comment]
> Same issue here. Probably something to do with the redirection. If you browse to the ZAPI_URL you will be redirected to the right site. If you disable Java Script you will not be redirected. Same behavior as with the `urlopen` function and you have to choose the destination (int, ch, de). On this page the `appToken` isn't available.
> 
> Change the URL in `resources/lib/core/zapisession.py`:
> 
> ```
> 100	handle = urllib2.urlopen(self.ZAPI_URL + '/ch/')
> ```
> 
> Work for me, but depend on the country.

Thanks for your answer. It's work fine 👍🏽

**Comment by stevenliatti** [comment]
> Same issue here. Probably something to do with the redirection. If you browse to the ZAPI_URL you will be redirected to the right site. If you disable Java Script you will not be redirected. Same behavior as with the `urlopen` function and you have to choose the destination (int, ch, de). On this page the `appToken` isn't available.
> 
> Change the URL in `resources/lib/core/zapisession.py`:
> 
> ```
> 100	handle = urllib2.urlopen(self.ZAPI_URL + '/ch/')
> ```
> 
> Work for me, but depend on the country.

Thank you, this work for me too :+1:

**Comment by xAlban** [comment]
Hello, Do you think this fixed will be pushed soon ? I'm using the plugin from the Kodi Add on repository and I have this error I think. I can't build a version with the fix because it's not for my device...

**Comment by evoisard** [comment]
Rolf's fix worked for me too. My girlfriend is happy :-)
Thanks!

**Comment by developerrespig** [comment]
Why do you just close this issue? This is a blocker for everyone who starts using this plugin and it has to be fixed!

**Comment by flabb17** [comment]
Quick Fix Works for me too
Thanks !

Le ven. 10 avr. 2020 à 18:53, Martin Gypser <notifications@github.com> a
écrit :

**Comment by dinoglobetrotter** [comment]
Thanks @rolfbachmann - works perfectly :+1:

**Comment by nancpasc** [comment]
Thank you everyone for your contribution. I'll try to fix this asap.

**Comment by nancpasc** [comment]
The update has been merged in the official repository. v1.0.6 should be made available soon.

**Comment by dairefagan** [comment]
Thanks, fix worked for me.

**Comment by nancpasc** [comment]
Thank you everyone for the support, the last update did fix the issue :)
However, this plugin won't be upgraded to work in Kodi 19+

Check the excellent Zattoo PVR Client here for a lof of cool features :
https://kodi.tv/addon/pvr-client/zattoo-pvr-client
