### ISSUE TITLE
Error playlist player

### ISSUE THREAD

**Issue by ulissesss** [nancpasc/ZattooBox#44]
hello, today I was trying to watch some channels and I got this error:

2021-02-10 20:48:03.701 T:1916403728   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=rai-uno]

**Comment by wama68** [comment]
Same issue here since yesterday.

**Comment by adamprice2** [comment]
Just adding that I'm getting the same issue here.

The issue seems to be that Zattoo no longer support hls streams only hls5 or hls7.
trivial fix was to change hls to hls5

Patch file here
```From 3f8806a3b61ddfa3cab5427798d4e6614a187e30 Mon Sep 17 00:00:00 2001
From: Adam Price <dummy@example.com>
Date: Fri, 12 Feb 2021 06:47:16 +0100
Subject: [PATCH] Change hls to hls5

---
 resources/lib/extensions/livetv.py     | 2 +-
 resources/lib/extensions/recordings.py | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/resources/lib/extensions/livetv.py b/resources/lib/extensions/livetv.py
index ce5ef2c..ec61a75 100644
--- a/resources/lib/extensions/livetv.py
+++ b/resources/lib/extensions/livetv.py
@@ -62,7 +62,7 @@ class LiveTV(ZBExtension):
                self.ZBProxy.add_directoryItems(items)

        def watch(self, args):
-               params = {'cid': args['id'], 'stream_type': 'hls'}
+               params = {'cid': args['id'], 'stream_type': 'hls5'}
                resultData = self.ZapiSession.exec_zapiCall('/zapi/watch', params)
                if resultData is not None:
                        url = resultData['stream']['watch_urls'][0]['url']
diff --git a/resources/lib/extensions/recordings.py b/resources/lib/extensions/recordings.py
index 0c47db9..ee7af4d 100644
--- a/resources/lib/extensions/recordings.py
+++ b/resources/lib/extensions/recordings.py
@@ -53,7 +53,7 @@ class Recordings(ZBExtension):
                self.ZBProxy.add_directoryItems(recordings)

        def watch(self, args):
-               params = {'recording_id': args['id'], 'stream_type': 'hls'}
+               params = {'recording_id': args['id'], 'stream_type': 'hls5'}
                resultData = self.ZapiSession.exec_zapiCall('/zapi/watch', params)
                if resultData is not None:
                        url = resultData['stream']['url']
--
2.25.1

```

**Comment by bl00dy1837** [comment]
> Just adding that I'm getting the same issue here.
> 
> The issue seems to be that Zattoo no longer support hls streams only hls5 or hls7.
> trivial fix was to change hls to hls5
> 
> Patch file here
> 
> ```
> From: Adam Price <dummy@example.com>
> Date: Fri, 12 Feb 2021 06:47:16 +0100
> Subject: [PATCH] Change hls to hls5
> 
> ---
>  resources/lib/extensions/livetv.py     | 2 +-
>  resources/lib/extensions/recordings.py | 2 +-
>  2 files changed, 2 insertions(+), 2 deletions(-)
> 
> diff --git a/resources/lib/extensions/livetv.py b/resources/lib/extensions/livetv.py
> index ce5ef2c..ec61a75 100644
> --- a/resources/lib/extensions/livetv.py
> +++ b/resources/lib/extensions/livetv.py
> @@ -62,7 +62,7 @@ class LiveTV(ZBExtension):
>                 self.ZBProxy.add_directoryItems(items)
> 
>         def watch(self, args):
> -               params = {'cid': args['id'], 'stream_type': 'hls'}
> +               params = {'cid': args['id'], 'stream_type': 'hls5'}
>                 resultData = self.ZapiSession.exec_zapiCall('/zapi/watch', params)
>                 if resultData is not None:
>                         url = resultData['stream']['watch_urls'][0]['url']
> diff --git a/resources/lib/extensions/recordings.py b/resources/lib/extensions/recordings.py
> index 0c47db9..ee7af4d 100644
> --- a/resources/lib/extensions/recordings.py
> +++ b/resources/lib/extensions/recordings.py
> @@ -53,7 +53,7 @@ class Recordings(ZBExtension):
>                 self.ZBProxy.add_directoryItems(recordings)
> 
>         def watch(self, args):
> -               params = {'recording_id': args['id'], 'stream_type': 'hls'}
> +               params = {'recording_id': args['id'], 'stream_type': 'hls5'}
>                 resultData = self.ZapiSession.exec_zapiCall('/zapi/watch', params)
>                 if resultData is not None:
>                         url = resultData['stream']['url']
> --
> 2.25.1
> ```

thx. the workaround works for me.

**Comment by fxizel** [comment]
Thanks for the solution 👍
The path in librelec is "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/extensions/"

**Comment by ulissesss** [comment]
Hi, I edited livetv.py and recordings.py, now I got this error:

2021-02-12 16:45:47.274 T:1916096528  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=rai-due
2021-02-12 16:45:50.284 T:1296896224  NOTICE: Creating InputStream
2021-02-12 16:45:52.464 T:1296896224  NOTICE: Creating Demuxer
2021-02-12 16:46:22.502 T:1296896224   ERROR: OpenDemuxStream - Error creating demuxer
2021-02-12 16:46:22.668 T:1296896224  NOTICE: CVideoPlayer::OnExit()
2021-02-12 16:46:22.747 T:1916096528  NOTICE: CVideoPlayer::CloseFile()
2021-02-12 16:46:22.747 T:1916096528  NOTICE: VideoPlayer: waiting for threads to exit
2021-02-12 16:46:22.747 T:1916096528  NOTICE: VideoPlayer: finished waiting

**Comment by adamprice2** [comment]
Sorry mate it's all working for me now, so you are on your own there.
For basic troubleshooting though, can you confirm that it works OK for you via a web-browser on a windows PC?
Until that works, you can probably be sure the issue is not with the Kodi plugin.

**Comment by ulissesss** [comment]
Yes , I dont have any issue via web browser. Sometimes the plugin works but most of the time I have that error. I use nordvpn.. Do you use any vpn?

**Comment by adamprice2** [comment]
No I don't need a VPN. If you are using it via a VPN then it's not a supported config, so I may not be much help.
The second set of errors you posted looks like kodi can't process the stream it is being passed, there are loads of reasons this could be the case and I am not going to even try to fix it for you.

**Comment by ulissesss** [comment]
I fixed it, i had an issue with the dns server, thank you :-)
