### ISSUE TITLE
Zattoo Box Missing from Kodi Repository

### ISSUE THREAD

**Issue by bajjohn1** [nancpasc/ZattooBox#5]
Hi, I can't live without the Zattoo Box addon. But I recently upgraded to Kodi/Helix/14.0/Openelec 5.0.0 on the raspberry pi and cant find Zattoo Box in the default Kodi repository. Can you tell me what is happening here?
thanks

**Comment by nancpasc** [comment]
Hi. I've noticed a bug with the plugin when running in Kodi 14 and Windows 8.1, this is why it's not in the repository yet. However, you should be able to use it if you download and install the plugin manually. Can you tell me if it's working for you ? Some people reported that it worked fine. If it's ok I'll add the plugin in the Helix repository. Thanks.

**Comment by nancpasc** [comment]
Added in Kodi Helix.
Regards.
