### ISSUE TITLE
favorites filter not working

### ISSUE THREAD

**Issue by chrzechmeister** [nancpasc/ZattooBox#6]
hi, thanks for this great add-on .. works great. I have one problem though, the favorite list is not working for me .. I can save channels but if I open the favorite list it is always empty. My system runs on openELEC 5.0.5 on a raspberry pi b+.

regards,
christoph

**Comment by nancpasc** [comment]
Hi. The favorites channels cache is automatically updated from time to time, it might solve the issue within 2 days. Otherwise remove manually all the cache files (*.cache) in the zattoobox data folder.

Regards.
P.
