### ISSUE TITLE
Plugin does not work with VU+ VTI 8.1 and XBMC

### ISSUE THREAD

**Issue by bueste** [nancpasc/ZattooBox#7]
Hi
Thanks for your work on this pluing. Great work.

I can connect to zatoo and see the channels. If i put on a channel ok, the screen will be black and nothing  will do. Pls fix it.
Thx

**Comment by nancpasc** [comment]
Hi.

There are devices the plugin won't work with. I can't fix this behavior. Check maybe if firmware/software updates are available for your system.

Regards.
P.

**Comment by bueste** [comment]
Hi
Does it not work with XMBC 13.2?
Thx

**Comment by nancpasc** [comment]
Yes works fine

**Comment by bueste** [comment]
Ok. What could I do, that it works on my vti 8.1?
I see the channels, If i put ok, it will be black. If I put ok agian, I see the Mediaplayer which display Playlist "live.m3u8?maxrate=900&sig=81f7513ba60ec5ca25c8"

**Comment by nancpasc** [comment]
I had a similar issue with a Windows 8.1 workstation. It's related to a Kodi streaming feature and no fix within the plugin would help. The only solution for now is to patch with newer firmware and software, as mentioned.

http://trac.kodi.tv/ticket/15607
