### ISSUE TITLE
Use with FTVGuide

### ISSUE THREAD

**Issue by bluezed** [nancpasc/ZattooBox#8]
Hello,
Sorry for contacting you through here but I hope you can help...

I'm one of the developers of the FTVGuide addon for Kodi (https://github.com/bluezed/FTV-Guide-Repo) and we added support for your Zattoo Box a while ago meaning that users could start watching streams through Zattoo Box directly from our programme guide if they had your addon installed. 
We also support FilmOn.tv and USTVNow and a few others too...

Anyway... since the update to v1.0.0 the streams are no longer starting. Users get a black screen for a few seconds and then come back to the guide. There's not a lot in the log but here's the debug log from one of the users who reported the issue: http://pastebin.com/wSNGRcPe

Could you maybe let us know if there's anything we can do on our side to get this working again?

Many thanks!

**Comment by nancpasc** [comment]
Hi,

First of all, thank you for integrating ZB in your addon :) The TV guide is a must-have and I wanted to add that feature for some time so I'll investigate and see how the issue can be fixed.

If everything works seamlessly, I would like to make a direct bridge between the two plugins, using dependencies. Is it available in official repository yet ? 

Regards,

P.

**Comment by bluezed** [comment]
Hi again and thanks for your reply :)

It'd be great if we could directly support your addon just let me know what you need for that.

The FTV Guide is basically a fork of the original TVGuide made by Tommy Winther (https://github.com/twinther/script.tvguide) which we've developed a bit further since. Unfortunately it's not in the official Repo. Currently it's released on tvaddons.ag and in their Fusion installer. Here's our support forum for it: http://forums.tvaddons.ag/forums/181-FTV-GUIDE-FOR-KODI

Let me know if I can do anything to help.

**Comment by nancpasc** [comment]
Ok I'll have a look to see what needs to be fixed in the next few days.

**Comment by nancpasc** [comment]
Hi.

I found the issue. Starting from V1.0.0, I slightly changed the parameters used to call the stream. Please switch to this new format :

plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=[channel_id]

The channel_id parameter is the same than older versions.

Regards,

PN.

**Comment by nancpasc** [comment]
Don't use the brackets though : plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=channel_id

**Comment by bluezed** [comment]
Thanks a lot! 

We've updated the call now and it's working again :)

If you're still interested in building the "bridge" let me know!

Cheers

**Comment by nancpasc** [comment]
Glad to hear. Yes I'll look into when I have some time.
